### ISSUE TITLE
Theme updates each time I switch text channel

### ISSUE THREAD

**Issue by masterw3x** [IRDeNial/BD-Server-Themes#8]
Hi! First like to thank you for making this extension! Really neat stuff!

I am using the Clear Vision theme and am not sure if this applies to all themes, but when I switch channels on a server with a specific theme it keeps on reloading the assets. It gets to be really annoying, so please fix this. It would be nice if it preloaded all the themes at start and new which servers to display, instead of having to load the theme each time I switch.

Thanks,

Master Wex

**Comment by IRDeNial** [comment]
The problem with having all themes loaded initially is that it would require modification of elements that discord itself & other themes rely on.

Seems like it's just a poor implementation of the theme.  From my memory, Clear Vision loads everything through a @import directive, so there wouldn't be much I can do from my end anyways.
Please correct me if I'm wrong.

**Comment by masterw3x** [comment]
Is there any themes you suggest that are more compatible with your plugin?

**Comment by IRDeNial** [comment]
Any theme is technically compatible.
Try to find themes that don't rely on loading external resources.

Best regards,
Michael Orozco

**Comment by masterw3x** [comment]
Ok thanks. Very fast response!

**Comment by TheDarkBomber** [comment]
@masterw3x This is fixed in the [forked version of this plugin](https://github.com/TheDarkBomber/BD-Server-Themes) which is actively being worked on. It fixes the problem by simply checking whether the user is on a different server or not before loading the theme. If the user has switched to a different server, it loads the theme. If the user has only switched channels within the server, it doesn't reload the theme, it keeps it from when the user initially loaded the theme.
